### ISSUE TITLE
Security warning on staging site

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#175]
Tania at CZI reported last night: I get a security warning when I click on this link: "This site is blocked due to a security threat."

I can not reproduce

**Comment by jay-hodgson** [comment]
Met with Hayley Brooks from CZI, and found it's because the Cisco Umbrella service has flagged our domain (or perhaps just ip) as malware.  It seems likely to be an IP issue, since our site is distributed via Amazon CloudFront CDN, so the edge servers are almost certainly serving other malware sites.  Hayley opened an IT ticket on their side, and clicked the Report an Incorrect Block to the Cisco Umbrella service, so hopefully this will be resolved on their side.  Not sure there's much we can do.  Here's the diagnostic info for the Cisco Umbrella error response:
<img width="713" alt="Screen Shot 2020-05-15 at 4 03 05 PM" src="https://user-images.githubusercontent.com/1864447/82103436-d71ece00-96c7-11ea-9936-0871a6280e8c.png">

**Comment by conundrumgirl** [comment]
won't fix
