### ISSUE TITLE
Dan't have email screen- copy edits

### ISSUE THREAD

**Issue by vbarone00** [Sage-Bionetworks/covidrecoverycorps#189]
Revise to add paragraphs:

At this time, we are only able to invite participants to lab draws with an email account. 

We are working on this issue. We hope to support scheduling appointments with your phone number in the near future. 

You can still provide important information to our researchers by filling out surveys.

**Comment by flylikeabirdfloatlikeabuoy** [comment]
@vbarone00  I added : you can still join the COVID Recovery Corps ---because I thought it wasn't clear that they would still be part of it.

"At this time, we are only able to invite participants to lab draws with an email account. 

We are working on this issue. We hope to support scheduling appointments with your phone number in the near future. 

You can still join the COVID Recovery Corps and provide important information to our researchers by filling out surveys with your phone number."
![Screen Shot 2020-05-16 at 2 25 48 PM](https://user-images.githubusercontent.com/64874011/82130543-24ab4180-9781-11ea-97b6-a85a40d73d2e.png)
