### ISSUE TITLE
Logging out and back in during HIPAA authorization loses state

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#404]
Repro: Log out and back in after you have agreed to do the HIPAA authorization but before you complete the process. You are then taken to the survey dashboard. The consent in HIPAA is marked agreed, but I never actually signed. This is very problematic legal situation to be in.

Logging out and back in during this state should restart the HIPAA authorization process.

**Comment by conundrumgirl** [comment]
@mkellen , were you signing up as a new user or did you do it through the account settings?

**Comment by mkellen** [comment]
I signed up as a new user, completed the consent, started the HIPAA auth, logged out, and then logged in.

**Comment by conundrumgirl** [comment]
@mkellen , is there any way we could walk through it together? I am not able to recreate this behavior and I can not think of a way if can happen from the code perspective.
If the user logs out during the HIPAA consent, when they log back in it does indeed take them to the dashboard. But they are not HIPAA consented.
The login starts in a different session so we don't keep track of where they were. It is different with the study consent since it's necessary for any action. So when non-consented user logs back in, we check their profile and take them to the consent flow.

**Comment by conundrumgirl** [comment]
could not reproduce
