### ISSUE TITLE
Header text on mobile hompage

### ISSUE THREAD

**Issue by hayleybr00ks** [Sage-Bionetworks/covidrecoverycorps#433]
Header text on mobile (building a partnership between COVID-19 survivors and researchers) covers photos. Is there an option to put the text either above or below the photos on mobile?

**Comment by jay-hodgson** [comment]
@flylikeabirdfloatlikeabuoy : Need some guidance here, since the color of the white text also probably needs to change.  What do you think?

**Comment by mkellen** [comment]
I'm not sure worth doing anything on this one.... Lynn?

**Comment by flylikeabirdfloatlikeabuoy** [comment]
![Screen Shot 2020-06-01 at 3 35 55 PM](https://user-images.githubusercontent.com/64874011/83461431-96d88300-a41d-11ea-84e8-a9e31fcfda0a.png)


@jay-hodgson  Is it possible to crop the mobile so that it is framed where the faces are more to the right side?  I'll link you to figma file with this recommendation. Thanks!

**Comment by flylikeabirdfloatlikeabuoy** [comment]
I think what we have is now an improvement. Closing this ticket
