### ISSUE TITLE
Spanish language version of the site

### ISSUE THREAD

**Issue by mkellen** [Sage-Bionetworks/covidrecoverycorps#454]
It is important that we be able to go into the Latinx community with a Spanish language version of the  study fairly quickly, although the exact timing of outreach here is still TBD.

Wendy has access to people that can translate the copy, and we're still waiting to finalize the copy.

Cutting the ticket so we start thinking about our technical approach to localization, although engineering can't yet take all the needed steps to achieve it.

Feel free to break up into smaller tickets - I'm not sure what if anything is the GitHub equivalent of an epic.

**Comment by conundrumgirl** [comment]
Just want to outline at the high level what needs to be done:
 - Add  "react-i18next" to the project and setup the top level configuration
 - Add the language-switcher component to the top nav area
-  Pull out all the text strings from pages into the en json file(s) and replace them with appropriate l18n syntax(the difficulty of this task will vary depending on how intermingled the mark-up is with the text but this is by far the most time consuming of all tasks.
- For surveys we need a mechanism for serving appropriate JSON files depending on location 

All this work needs be done before we request spanish translation to be most efficient.  Ideally we would have the en. json files to pass to the translator and as a result we would get the equivalent files in spanish. That way all we would need to do is to drop them in.
@mkellen @jay-hodgson

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Keeping the UI simple here since it's just 2 languages.
When they arrive into the English page --- we write "en español" . When they switch to Spanish version, we write "in English" 
![Screen Shot 2020-06-03 at 12 09 57 PM](https://user-images.githubusercontent.com/64874011/83678793-25badc00-a593-11ea-9dfe-a90a0bd53b68.png)

![Screen Shot 2020-06-03 at 12 10 06 PM](https://user-images.githubusercontent.com/64874011/83678805-2a7f9000-a593-11ea-8d09-6097ed92e3d5.png)

**Comment by conundrumgirl** [comment]
Love it! Gracias.
