### ISSUE TITLE
Urgent Survey 2 Q6; should be check all that apply 

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#518]
Please change into checkbox and add "(check all that apply)" to the question

If they select the non-testing choices, it should deselect the tests. 

![image](https://user-images.githubusercontent.com/64874011/84524147-5505d300-ac8e-11ea-88fa-6e2e5b962c35.png)

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Also "Serum antibody tests"  should be "test"

**Comment by conundrumgirl** [comment]
@flylikeabirdfloatlikeabuoy  - there is more to this change than just swapping radios for checkboxes. It means that we can have two different dates from nasal swabs and blood test. So I will need to rework this question to look more like question 5 -- with a subquestion showing up underneath.  If you can mock up the new UI it would be great - otherwise I'll just follow the pattern on question 5.

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Yeah sorry that I didn't catch this earlier. I think since the launch has been delayed, there is a high possibility that people have had more than one type of test by now.  

If you could follow existing check mark box patterns that would be greatly be appreciated. Thanks

**Comment by conundrumgirl** [comment]
No apology needed. It's a very good point. Wondering if it will affect the participant UI and @itismeghasyam 's work since the data object shape changes slightly as a result. I'll bring it up.
