### ISSUE TITLE
New UI for giftcard

### ISSUE THREAD

**Issue by vbarone00** [Sage-Bionetworks/covidrecoverycorps#526]
We need to introduce new UI to alert the users to what they need to do for a gift card. 

To be invited for a lab test, you will need to complete surveys 1-3. To qualify for a gift card, you will also need to provide a sample and complete surveys 4 and 5.

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Just synced up with Vanessa on how we might be able to resolve this: 

1. Main dashboard: 

"The information you provide will help researchers learn more about COVID-19.

To be invited for an antibody test, you will need to provide your contact information and complete surveys 1 & 2. "

------
2. After Surveys 1 & 2 completed: 

"Lab Preferences

You’ve completed the minimum surveys to qualify for the antibody test waitlist. 

To receive a gift card, you will need to be invited to an antibody test and provide a biosample. You will also need to complete surveys 3 & 4. 

We cannot guarantee testing invites for all participants at this time. 

If you were invited to get an antibody test, what is your testing preference? "

-----
3. If selected a lab draw/at home test kit: 

Thank you!

We’ve added you to the waitlist for an antibody test. If you are selected, you will receive an email.

-----
4. If they didn't selected testing: 

Thank you!

Please consider completing the rest of the surveys if you have time.

---

<img width="1139" alt="Screen Shot 2020-06-15 at 6 20 21 PM" src="https://user-images.githubusercontent.com/64874011/84721185-ed24e600-af34-11ea-8f6d-321d7b565c61.png">

5. If they were invited for lab draw: 

You’re invited!

Please complete surveys 3 & 4 before your antibody test appointment in order to receive a gift card. 

---
6. If they were invited for at home test kit: 

You’re invited!

Please complete surveys 3 & 4 before sending back your at-home test kit. 



<img width="582" alt="Screen Shot 2020-06-15 at 6 20 29 PM" src="https://user-images.githubusercontent.com/64874011/84721192-f0b86d00-af34-11ea-8c49-b6f1cb3fb265.png">

**Comment by flylikeabirdfloatlikeabuoy** [comment]
Reopening this ticket....
Not sure why I'm seeing this screen after I've completed survey 3 rather than the above flow...

<img width="669" alt="Screen Shot 2020-07-09 at 9 55 19 AM" src="https://user-images.githubusercontent.com/64874011/87068433-63caa180-c1ca-11ea-98e0-74f6fec94a95.png">

**Comment by flylikeabirdfloatlikeabuoy** [comment]
@conundrumgirl  Please pause on this work. I want to make sure we are properly accommodating scenarios for people who don't have email. Thanks

**Comment by conundrumgirl** [comment]
fixed @flylikeabirdfloatlikeabuoy please take another look
