### ISSUE TITLE
Survey 3: Covid Experience - limit ability to write letters into numerical fields

### ISSUE THREAD

**Issue by flylikeabirdfloatlikeabuoy** [Sage-Bionetworks/covidrecoverycorps#84]
![Screen Shot 2020-05-08 at 3 19 38 PM](https://user-images.githubusercontent.com/64874011/81453808-6a438b00-913f-11ea-9145-f5855410c883.png)

Let's make sure we get clean data with numerical input fields such as "For How many days" as well as temperature values. Right now I can type anything! :)

**Comment by jay-hodgson** [comment]
This is a bug.  
While Chrome and Edge do not allow alpha characters in number type input fields, FF and Safari unfortunately do ([try it out!](https://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_number)). 
I think in order to fix this in the forms library we would need a custom editor for this json field type, where we'd need to add our own keypress event handler (and eat any character that does not conform to a regex).

**Comment by conundrumgirl** [comment]
dealt with by validation. won't fix
